#!/usr/bin/env node
'use strict';

const _ = require('underscore');
const nfsevents = require('.');

nfsevents.shouldLog = true;

const ARGV = process.argv;
const mode = ARGV[2];

const USAGE = [
  'Usage: nfsevents publish [path1 path2 ...]',
  '       nfsevents subscribe [url [path1 path2 ...]]'
].join('\n');

if (mode === 'publish') {
  nfsevents.publish({paths: ARGV.slice(3)});
} else if (mode === 'subscribe') {
  nfsevents.subscribe({url: ARGV[3], paths: ARGV.slice(4)}, _.noop);
} else if (!mode) {
  console.error(USAGE);
} else {
  console.error(`Unknown mode: "${mode}"`);
}
